package br.gov.saude.servicos.cnes.v1r0.leitoservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10 2018-04-10T14:07:27.411-03:00
 * Generated source version: 3.1.10
 *
 */
@WebService(targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/leitoservice", name = "LeitoServicePortType")
@XmlSeeAlso({br.gov.saude.servicos.schema.cnes.v1r0.codigocnes.ObjectFactory.class, ObjectFactory.class, br.gov.saude.servicos.wsdl.mensageria.falha.v5r0.msfalha.ObjectFactory.class, br.gov.saude.servicos.schema.cnes.v1r0.leito.ObjectFactory.class, br.gov.saude.servicos.wsdl.mensageria.falha.v5r0.mensagem.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LeitoServicePortType {

    /**
     * Consultar os leitos do Estabelecimento de Saude pelo código do CNES.
     *
     */
    @WebMethod
    @WebResult(name = "responseConsultarLeitosCNES", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/leitoservice", partName = "responseConsultarLeitosCNES")
    public ResponseConsultarLeitosCNES consultarLeitosCNES(
            @WebParam(partName = "requestConsultarLeitosCNES", name = "requestConsultarLeitosCNES", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/leitoservice") RequestConsultarLeitosCNES requestConsultarLeitosCNES
    ) throws LeitoFault;
}
