package br.gov.saude.servicos.cnes.v1r0.estabelecimentosaudeservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-04-10T14:07:01.056-03:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "EstabelecimentoSaudeService", 
                  wsdlLocation = "https://servicoshm.saude.gov.br/cnes/EstabelecimentoSaudeService/v1r0?wsdl",
                  targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice") 
public class EstabelecimentoSaudeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", "EstabelecimentoSaudeService");
    public final static QName EstabelecimentoSaudeServicePort = new QName("http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", "EstabelecimentoSaudeServicePort");
    public final static QName EstabelecimentoSaudeServiceSOAP11Port = new QName("http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", "EstabelecimentoSaudeServiceSOAP11Port");
    static {
        URL url = null;
        try {
            url = new URL("https://servicoshm.saude.gov.br/cnes/EstabelecimentoSaudeService/v1r0?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EstabelecimentoSaudeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://servicoshm.saude.gov.br/cnes/EstabelecimentoSaudeService/v1r0?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EstabelecimentoSaudeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EstabelecimentoSaudeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstabelecimentoSaudeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EstabelecimentoSaudeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EstabelecimentoSaudeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EstabelecimentoSaudeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns EstabelecimentoSaudeServicePortType
     */
    @WebEndpoint(name = "EstabelecimentoSaudeServicePort")
    public EstabelecimentoSaudeServicePortType getEstabelecimentoSaudeServicePort() {
        return super.getPort(EstabelecimentoSaudeServicePort, EstabelecimentoSaudeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstabelecimentoSaudeServicePortType
     */
    @WebEndpoint(name = "EstabelecimentoSaudeServicePort")
    public EstabelecimentoSaudeServicePortType getEstabelecimentoSaudeServicePort(WebServiceFeature... features) {
        return super.getPort(EstabelecimentoSaudeServicePort, EstabelecimentoSaudeServicePortType.class, features);
    }


    /**
     *
     * @return
     *     returns EstabelecimentoSaudeServicePortType
     */
    @WebEndpoint(name = "EstabelecimentoSaudeServiceSOAP11Port")
    public EstabelecimentoSaudeServicePortType getEstabelecimentoSaudeServiceSOAP11Port() {
        return super.getPort(EstabelecimentoSaudeServiceSOAP11Port, EstabelecimentoSaudeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstabelecimentoSaudeServicePortType
     */
    @WebEndpoint(name = "EstabelecimentoSaudeServiceSOAP11Port")
    public EstabelecimentoSaudeServicePortType getEstabelecimentoSaudeServiceSOAP11Port(WebServiceFeature... features) {
        return super.getPort(EstabelecimentoSaudeServiceSOAP11Port, EstabelecimentoSaudeServicePortType.class, features);
    }

}
