package br.jus.cnj.servico_intercomunicacao_2_2_2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2019-07-10T21:09:06.701-03:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "IntercomunicacaoService", 
                  wsdlLocation = "https://pje.tjro.jus.br/pg/intercomunicacao?wsdl",
                  targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/") 
public class IntercomunicacaoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", "IntercomunicacaoService");
    public final static QName IntercomunicacaoImplPort = new QName("http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", "IntercomunicacaoImplPort");
    static {
        URL url = null;
        try {
            url = new URL("https://pje.tjro.jus.br/pg/intercomunicacao?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IntercomunicacaoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://pje.tjro.jus.br/pg/intercomunicacao?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IntercomunicacaoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IntercomunicacaoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntercomunicacaoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IntercomunicacaoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IntercomunicacaoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IntercomunicacaoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ServicoIntercomunicacao222
     */
    @WebEndpoint(name = "IntercomunicacaoImplPort")
    public ServicoIntercomunicacao222 getIntercomunicacaoImplPort() {
        return super.getPort(IntercomunicacaoImplPort, ServicoIntercomunicacao222.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoIntercomunicacao222
     */
    @WebEndpoint(name = "IntercomunicacaoImplPort")
    public ServicoIntercomunicacao222 getIntercomunicacaoImplPort(WebServiceFeature... features) {
        return super.getPort(IntercomunicacaoImplPort, ServicoIntercomunicacao222.class, features);
    }

}
