package br.jus.cnj.servico_intercomunicacao_2_2_2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2019-07-10T21:09:06.662-03:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", name = "servico-intercomunicacao-2.2.2")
@XmlSeeAlso({br.jus.cnj.intercomunicacao_2_2.ObjectFactory.class, br.jus.cnj.tipos_servico_intercomunicacao_2_2.ObjectFactory.class, br.jus.cnj.servico_intercomunicacao_2_2.ObjectFactory.class, br.jus.cnj.mni.cda.ObjectFactory.class})
public interface ServicoIntercomunicacao222 {

    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/consultarAlteracao")
    @RequestWrapper(localName = "consultarAlteracao", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarAlteracao")
    @ResponseWrapper(localName = "consultarAlteracaoResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarAlteracaoResposta")
    public void consultarAlteracao(
        @WebParam(name = "idConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String idConsultante,
        @WebParam(name = "senhaConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String senhaConsultante,
        @WebParam(name = "numeroProcesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String numeroProcesso,
        @WebParam(mode = WebParam.Mode.OUT, name = "sucesso", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> sucesso,
        @WebParam(mode = WebParam.Mode.OUT, name = "mensagem", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> mensagem,
        @WebParam(mode = WebParam.Mode.OUT, name = "hashCabecalho", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> hashCabecalho,
        @WebParam(mode = WebParam.Mode.OUT, name = "hashMovimentacoes", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> hashMovimentacoes,
        @WebParam(mode = WebParam.Mode.OUT, name = "hashDocumentos", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> hashDocumentos
    );

    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/confirmarRecebimento")
    @RequestWrapper(localName = "confirmarRecebimento", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConfirmarRecebimento")
    @ResponseWrapper(localName = "confirmarRecebimentoResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConfirmarRecebimentoResposta")
    public void confirmarRecebimento(
        @WebParam(name = "idRecebedor", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String idRecebedor,
        @WebParam(name = "senhaRecebedor", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String senhaRecebedor,
        @WebParam(name = "protocolo", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String protocolo,
        @WebParam(mode = WebParam.Mode.OUT, name = "sucesso", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> sucesso,
        @WebParam(mode = WebParam.Mode.OUT, name = "mensagem", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> mensagem
    );

    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/consultarAvisosPendentes")
    @RequestWrapper(localName = "consultarAvisosPendentes", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarAvisosPendentes")
    @ResponseWrapper(localName = "consultarAvisosPendentesResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarAvisosPendentesResposta")
    public void consultarAvisosPendentes(
        @WebParam(name = "idRepresentado", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String idRepresentado,
        @WebParam(name = "idConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String idConsultante,
        @WebParam(name = "senhaConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String senhaConsultante,
        @WebParam(name = "dataReferencia", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String dataReferencia,
        @WebParam(mode = WebParam.Mode.OUT, name = "sucesso", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> sucesso,
        @WebParam(mode = WebParam.Mode.OUT, name = "mensagem", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> mensagem,
        @WebParam(mode = WebParam.Mode.OUT, name = "aviso", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<br.jus.cnj.intercomunicacao_2_2.TipoAvisoComunicacaoPendente>> aviso
    );

    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/consultarProcesso")
    @RequestWrapper(localName = "consultarProcesso", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarProcesso")
    @ResponseWrapper(localName = "consultarProcessoResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarProcessoResposta")
    public void consultarProcesso(
        @WebParam(name = "idConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String idConsultante,
        @WebParam(name = "senhaConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String senhaConsultante,
        @WebParam(name = "numeroProcesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String numeroProcesso,
        @WebParam(name = "dataReferencia", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String dataReferencia,
        @WebParam(name = "movimentos", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.Boolean movimentos,
        @WebParam(name = "incluirCabecalho", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.Boolean incluirCabecalho,
        @WebParam(name = "incluirDocumentos", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.Boolean incluirDocumentos,
        @WebParam(name = "documento", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.util.List<java.lang.String> documento,
        @WebParam(mode = WebParam.Mode.OUT, name = "sucesso", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> sucesso,
        @WebParam(mode = WebParam.Mode.OUT, name = "mensagem", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> mensagem,
        @WebParam(mode = WebParam.Mode.OUT, name = "processo", targetNamespace = "")
        javax.xml.ws.Holder<br.jus.cnj.intercomunicacao_2_2.TipoProcessoJudicial> processo
    );

    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/consultarTeorComunicacao")
    @RequestWrapper(localName = "consultarTeorComunicacao", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarTeorComunicacao")
    @ResponseWrapper(localName = "consultarTeorComunicacaoResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarTeorComunicacaoResposta")
    public void consultarTeorComunicacao(
        @WebParam(name = "idConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String idConsultante,
        @WebParam(name = "senhaConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String senhaConsultante,
        @WebParam(name = "numeroProcesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String numeroProcesso,
        @WebParam(name = "identificadorAviso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String identificadorAviso,
        @WebParam(mode = WebParam.Mode.OUT, name = "sucesso", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> sucesso,
        @WebParam(mode = WebParam.Mode.OUT, name = "mensagem", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> mensagem,
        @WebParam(mode = WebParam.Mode.OUT, name = "comunicacao", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<br.jus.cnj.intercomunicacao_2_2.TipoComunicacaoProcessual>> comunicacao
    );

    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/entregarManifestacaoProcessual")
    @RequestWrapper(localName = "entregarManifestacaoProcessual", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoEntregarManifestacaoProcessual")
    @ResponseWrapper(localName = "entregarManifestacaoProcessualResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoEntregarManifestacaoProcessualResposta")
    public void entregarManifestacaoProcessual(
        @WebParam(name = "idManifestante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String idManifestante,
        @WebParam(name = "senhaManifestante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String senhaManifestante,
        @WebParam(name = "numeroProcesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String numeroProcesso,
        @WebParam(name = "dadosBasicos", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        br.jus.cnj.intercomunicacao_2_2.TipoCabecalhoProcesso dadosBasicos,
        @WebParam(name = "documento", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.util.List<br.jus.cnj.intercomunicacao_2_2.TipoDocumento> documento,
        @WebParam(name = "dataEnvio", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.lang.String dataEnvio,
        @WebParam(name = "parametros", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        java.util.List<br.jus.cnj.intercomunicacao_2_2.TipoParametro> parametros,
        @WebParam(mode = WebParam.Mode.OUT, name = "sucesso", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> sucesso,
        @WebParam(mode = WebParam.Mode.OUT, name = "mensagem", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> mensagem,
        @WebParam(mode = WebParam.Mode.OUT, name = "protocoloRecebimento", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> protocoloRecebimento,
        @WebParam(mode = WebParam.Mode.OUT, name = "dataOperacao", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dataOperacao,
        @WebParam(mode = WebParam.Mode.OUT, name = "recibo", targetNamespace = "")
        javax.xml.ws.Holder<javax.activation.DataHandler> recibo,
        @WebParam(mode = WebParam.Mode.OUT, name = "parametro", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<br.jus.cnj.intercomunicacao_2_2.TipoParametro>> parametro
    );
}
