<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://servicos.saude.gov.br/cnes/v1r0/equipamentoservice" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:equipamento="http://servicos.saude.gov.br/schema/cnes/v1r0/equipamento" xmlns:cnes="http://servicos.saude.gov.br/schema/cnes/v1r0/codigocnes" xmlns:msfalha="http://servicos.saude.gov.br/wsdl/mensageria/falha/v5r0/msfalha" name="equipamento.v1r0" targetNamespace="http://servicos.saude.gov.br/cnes/v1r0/equipamentoservice">

    <wsdl:types>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://servicos.saude.gov.br/cnes/v1r0/equipamentoservice">

            <xs:import id="cnes" namespace="http://servicos.saude.gov.br/schema/cnes/v1r0/codigocnes" schemaLocation="https://servicoshm.saude.gov.br/cnes/EquipamentoService/v1r0?WSDL&amp;type=XSD&amp;file=file%3A%2FC%3A%2FUsers%2FAdministrador%2FDownloads%2FOAG_20160318_11-20%2FRESOURCES50%2Fxsd%2Fcnes%2Fcodigocnes.v1r0.xsd"/>

            <xs:import id="msfalha" namespace="http://servicos.saude.gov.br/wsdl/mensageria/falha/v5r0/msfalha" schemaLocation="https://servicoshm.saude.gov.br/cnes/EquipamentoService/v1r0?WSDL&amp;type=XSD&amp;file=file%3A%2FC%3A%2FUsers%2FAdministrador%2FDownloads%2FOAG_20160318_11-20%2FRESOURCES50%2Fxsd%2Fmensageria%2Ffalha%2Fmsfalha.v5r0.xsd"/>

            <xs:import id="equipamento" namespace="http://servicos.saude.gov.br/schema/cnes/v1r0/equipamento" schemaLocation="https://servicoshm.saude.gov.br/cnes/EquipamentoService/v1r0?WSDL&amp;type=XSD&amp;file=file%3A%2FC%3A%2FUsers%2FAdministrador%2FDownloads%2FOAG_20160318_11-20%2FRESOURCES50%2Fxsd%2Fcnes%2Fequipamentos%2Fequipamento.v1r0.xsd"/>

            <xs:element name="requestConsultarEquipamentos">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="1" maxOccurs="1" ref="cnes:CodigoCNES">
                            <xs:annotation>
                                <xs:documentation><![CDATA[Código do CNES]]></xs:documentation>
                            </xs:annotation>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="responseConsultarEquipamentos">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" maxOccurs="unbounded" ref="equipamento:Equipamento"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>

    <wsdl:message name="requestConsultarEquipamentos">
        <wsdl:part element="tns:requestConsultarEquipamentos" name="requestConsultarEquipamentos"/>
    </wsdl:message>

    <wsdl:message name="responseConsultarEquipamentos">
        <wsdl:part element="tns:responseConsultarEquipamentos" name="responseConsultarEquipamentos"/>
    </wsdl:message>

    <wsdl:message name="CnesFault">
        <wsdl:part name="fault" element="msfalha:MSFalha"/>
    </wsdl:message>

    <wsdl:portType name="EquipamentoServicePortType">
        <wsdl:operation name="consultarEquipamentos">
            <wsdl:input name="requestConsultarEquipamentos" message="tns:requestConsultarEquipamentos"/>
            <wsdl:output name="responseConsultarEquipamentos" message="tns:responseConsultarEquipamentos"/>
            <wsdl:fault name="CnesFault" message="tns:CnesFault"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="EquipamentoServiceSOAP12Binding" type="tns:EquipamentoServicePortType">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="consultarEquipamentos">
            <soap12:operation soapAction=""/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="CnesFault">
                <soap12:fault name="CnesFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
	
    <wsdl:binding name="EquipamentoServiceSOAP11Binding" type="tns:EquipamentoServicePortType">
        <soap11:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="consultarEquipamentos">
            <soap11:operation soapAction=""/>
            <wsdl:input>
                <soap11:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap11:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="CnesFault">
                <soap11:fault name="CnesFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
		
    </wsdl:binding>

    <wsdl:service name="EquipamentoService">
        <wsdl:port binding="tns:EquipamentoServiceSOAP12Binding" name="EquipamentoServicePort">
            <soap12:address location="https://servicoshm.saude.gov.br/cnes/EquipamentoService/v1r0"/>
        </wsdl:port>
        <wsdl:port binding="tns:EquipamentoServiceSOAP11Binding" name="EquipamentoServiceSOAP11Port">
            <soap11:address location="https://servicoshm.saude.gov.br/cnes/EquipamentoService/v1r0"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
